"""
Django settings for tracuse_project project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g6j=egk5eqp7q3390&$dv6*@j_5s13s%($660p=#bcq+p^2-1t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'components.common',
    'components.tracuser',
    'components.datum',
    'components.element_type',
    'components.element_value',
    'components.association',
    'components.filter',
    'components.watchword'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'config.urls'

TEMPLATE_PATH = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'tracuse',
        'USER': 'test',
        'PASSWORD': 'test',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Fixtures
FIXTURE_DIRS = (
    os.path.join(BASE_DIR, "fixtures"),
)


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'
STATIC_PATH = os.path.join(BASE_DIR, "assets")
STATICFILES_DIRS = (STATIC_PATH,)

# Custom data serializers
SERIALIZATION_MODULES = {
    "myjsonflat": "serializers.myjsonflat",
}

# Custom model groups
# Setup Models used for initial groups and types
MODEL_GROUPS = {
    "setup_data": [
        "auth.user",
        "datum.DatumGroup",
        "datum.DatumType",
        "element_type.ElementDataType",
        "element_type.ElementType",
        "element_type.ElementTypeDatumType",
        "element_type.ElementOption",
        "association.AssociationDirection"
    ],
    "sample_data": [
        "datum.DatumObject",
        "element_type.ElementTypeDatumObject",
        "element_value.ElementValueString",
        "element_value.ElementValueTextData",
        "element_value.ElementValueBoolean",
        "element_value.ElementValueDatetime",
        "element_value.ElementValueDecimal",
        "element_value.ElementValueBinary"
    ]
}
